# Ограничения длины полей
MAX_LENGTH_NAME = 200
MAX_LENGTH_SLUG = 32
MAX_LENGTH_TAG_NAME = 32
MAX_LENGTH_RECIPE_NAME = 256
MAX_LENGTH_INGREDIENT_NAME = 128
MAX_LENGTH_MEASUREMENT_UNIT = 64

# Ограничения для числовых полей
MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 32676  # Максимальное значение для PositiveSmallIntegerField
MIN_AMOUNT = 1
